### PR TITLE
Some adjustments in native implementations of Google and Facebook sigin.

### PR DESCRIPTION
**Pull request by micdoug**
Fix the problems mentioned in #39, #38 and #37.

### CODE REVIEW

**Comment by Clancey** [comment]
Thanks!

**Comment by micdoug** [comment]
This is a great library! Thank you.

**Comment by micdoug** [comment]
Did you update the nuget packages?

**Comment by Clancey** [comment]
Just updated them, you should see them live soon.

**Comment by micdoug** [comment]
Ok. Thanks.

**Pull request merged**
