### PR TITLE
Fix Dropbox Authentication -999 Error

### PR DESCRIPTION
**Pull request by allan-chin**
Ignore the "NSURLErrorDomain -999" authentication error with Dropbox. Issue #76.

James - it looks like the files from my previous pull (4871dac) might be include in the pull as well. The only file I changed in this pull is WebAuthenticator.cs.

When do you think the next NuGet version with the changes from the last, and this pull be built and made available from Nuget.org?

Thanks

Allan

### CODE REVIEW

**Comment by Clancey** [comment]
I see you have been making changes, is this ready to merge?

**Comment by allan-chin** [comment]
Hey James, 

I fixed the issue with the WebAuthenticatorBroker not working well for Instagram authentication. Basically, I created a custom broker which is invoked for Instagram only. I followed this article, [https://peterfoot.net/2019/03/13/webauthenticationbroker-and-github/](url). I'm still up with GitHub pull requests so this latest fix has been added to my existing branch. The new changes for the Instagram issue are in 5280e00, 9306a53, and 839bfd2.
Please take a look and merge if you see fit.

When do you think you'll be creating a new Nuget version?

Thanks

Allan

**Comment by allan-chin** [comment]
I’m just about to submit another pull request for the Instagram issue.

With all my changes, I think I’m ready to go for all we’re doing. Sorry for the multiple changes in that one branch. I haven’t had the time to figure out how to use Github effectively.

Thanks

Allan

**Comment by Clancey** [comment]
Not a problem, thanks for the pull request!

**Comment by Clancey** [comment]
@allan-chin Nuget was published!

**Comment by allan-chin** [comment]
Nice James! I’ll give 1.0.52 a spin tomorrow with my TH, and verify at least my fixes.

I’ll let you know.

Thanks

**Comment by allan-chin** [comment]
Hey @Clancey, I just submitted a new issue against 1.0.52. There's now an Instagram authentication issue on MacOS only. Please take a look, when you get a chance.

Thanks

**Pull request merged**
